spring:
  application:
    name: TicTacToe
  threads:
    virtual:
      enabled: true
server:
  port: 9092

logging:
  level:
    root: warn
    org:
      springframework:
        web:
          socket: debug